name: GDS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r tt/requirements.txt
      - name: Create user config
        run: ./tt/tt_tool.py --create-user-config
      - name: Install OpenLane
        run: pip install openlane==$OPENLANE2_TAG
      - name: Harden
        run: ./tt/tt_tool.py --harden
      - name: Run FPGA Simulation (Icarus Verilog)
        run: |
          iverilog -o sim.vv src/tt_um_counter.v src/testbench.v
          vvp sim.vv
          # Analiza los resultados de la simulación (opcional)
          # Por simplicidad, asumimos que si la simulación termina, pasa
          touch fpga_passed
      - name: Update FPGA Status Badge
        run: |
          if [ -f "fpga_passed" ]; then
            echo "FPGA_STATUS=passing" >> $GITHUB_ENV
          else
            echo "FPGA_STATUS=failing" >> $GITHUB_ENV
        fi
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hardened-netlist
          path: runs/wokwi/results/final/lef/*.lef
